FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o kafka-exporter .

FROM alpine:3.18
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/kafka-exporter .
COPY config.yaml /root/config.yaml

EXPOSE 9308
ENTRYPOINT ["./kafka-exporter"]